---
"/index.html":
  project: Zotero++
"/pdf.html":
  project: Zotero++
"/ascii-rename/index.html":
  project: ASCII rename
"/auto-index/index.html":
  project: Auto Index
"/better-bibtex/index.html":
  project: Better BibTeX
"/better-bibtex/Citation-Keys.html":
  project: Better BibTeX
"/better-bibtex/Customized-Exports.html":
  project: Better BibTeX
"/better-bibtex/Pull-Export.html":
  project: Better BibTeX
"/better-bibtex/Support-Request-Guidelines.html":
  project: Better BibTeX
"/debug-bridge/index.html":
  project: Debug Bridge
"/link-local-files/index.html":
  project: Link local files
"/opds/index.html":
  project: Zotero OPDS server
"/report-customizer/index.html":
  project: Report Customizer
